### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by leandrofriedrich** [rickliu2000/Lumia930Pkg#4] opened 2021-05-07 10:48 UTC
Hello there! I wanted to try this out but when i try to compile it i get the following error: 
``chaosleo07@chaosleo07-HP-Elite-7500-Series-MT:~/edk2$ build -a ARM -p Lumia930Pkg/Lumia930.dsc -t GCC5 -j$(nproc) -s -n 0
Build environment: Linux-5.4.0-72-generic-x86_64-with-elementary-5.1.7-hera
Build start time: 12:27:39, May.07 2021

WORKSPACE        = /home/chaosleo07/edk2
EDK_TOOLS_PATH   = /home/chaosleo07/edk2/BaseTools
CONF_PATH        = /home/chaosleo07/edk2/Conf
PYTHON_COMMAND   = /usr/bin/python3.6

Processing meta-data .
Architecture(s)  = ARM
Build target     = DEBUG
Toolchain        = GCC5

Active Platform          = /home/chaosleo07/edk2/Lumia930Pkg/Lumia930.dsc

build.py...
/home/chaosleo07/edk2/Lumia930Pkg/Lumia930.dsc(...): error 4000: Instance of library class [RegisterFilterLib] is not found
	in [/home/chaosleo07/edk2/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf] [ARM]
	consumed by module [/home/chaosleo07/edk2/Lumia930Pkg/PrePi/PrePi.inf]
 

- Failed -
Build end time: 12:27:39, May.07 2021
Build total time: 00:00:01
``

This is the Build command im using: 
`build -a ARM -p Lumia930Pkg/Lumia930.dsc -t GCC5 -j$(nproc) -s -n 0
`

what can i do to fix this

**Comment by leandrofriedrich** [comment] 2021-05-08 12:17
so i fixed those errors i guess  but now im getting this: https://pastebin.com/FFWA0RfV

**Comment by rickliu2000** [comment] 2021-05-08 13:22
Please make sure that you have the required libraries available. Issues not caused by this package should not be listed here. Therefore, I am closing this issue.

**Closed as completed by rickliu2000** 2021-05-08 13:22 UTC

**Comment by rickliu2000** [comment] 2021-05-08 13:29
> 
> 
> so i fixed those errors i guess but now im getting this: https://pastebin.com/FFWA0RfV

You can try to build it from EDK2 commits before mid 2020, since code may change rapidly in a big project like this. I will rebase this package to the latest UDK once available. However, no release has been made after udk2018.

**Comment by leandrofriedrich** [comment] 2021-05-08 13:46
![Screenshots_2021-05-08-15-46-12.png](https://user-images.githubusercontent.com/58913672/117541522-8c9f0b80-b014-11eb-9dc3-b8cb4ae26d7e.png)i have the feeling that this is why
